# Use new trusty images, should yield newer compilers and packages
sudo: false

# Use Linux unless specified otherwise
os: linux
dist: trusty

language: cpp

matrix:
  include:
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-7
            - cmake-data
            - cmake
      env:
        - COMPILER=g++-7
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
            - george-edison55-precise-backports
          packages:
            - clang-5.0
            - g++-5
            - cmake-data
            - cmake
      env:
        - COMPILER=clang++-5.0

before_install:


before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DCMAKE_CXX_COMPILER=$COMPILER -DBUILD_TESTS=ON
  - cd ..

script:
  - cd build
  - make
  - cd ..
  - ./build/bin/yagbe -p
