on:
  push:
    branches:
    - master
    - release/*
name: Build
jobs:
  gitHubActionForDocker:
    name: GitHub Action for Docker
    runs-on: ubuntu-latest
    container:
      image: docker://trzeci/emscripten
      volumes:
      - /src:/github/workspace
    steps:
    - uses: actions/checkout@master
    - name: Chmod scripts
      run: |
        chmod +x ./docker/docker_emscripten.sh
        chmod +x ./docker/build_debug.sh
        chmod +x ./docker/build.sh
    - name: Build
      run: |
        mkdir -p build
        cd build
        emcmake cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=make -G "Unix Makefiles"
        emmake make
