on:
  push:
    branches:
    - master
    - release/*
name: Build
jobs:
  gitHubActionForDocker:
    name: GitHub Action for Docker
    runs-on: ubuntu-latest
    container:
      image: docker://trzeci/emscripten
      volumes:
      - /src:/github/workspace
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: |
        mkdir -p build
        cd build
        emcmake cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=make -G "Unix Makefiles"
        emmake make
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build/bin/
    - name: Publish page
      uses: maxheld83/ghpages@v0.2.1
      env:
          BUILD_DIR: build/bin/
          GH_PAT: ${{ secrets.PAGE_PUBLISH }}
