on:
  push:
    branches:
    - master
    - release/*
name: Build
jobs:
  gitHubActionForDocker:
    name: GitHub Action for Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Chmod scripts
      run: |
        chmod +x ./docker/docker_emscripten.sh
        chmod +x ./docker/build_debug.sh
        chmod +x ./docker/build.sh
    - name: GitHub Action for Docker
      uses: docker://apiaryio/emcc
      with:
        entrypoint: ./docker/build.sh
        args: -v $(pwd):/src
