on:
  push:
  pull_request:
name: Build WASM
jobs:
  buildAndDeploy:
    name: Build WASM and deploy on page
    runs-on: ubuntu-latest
    container:
      image: docker://trzeci/emscripten
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build
      uses: lukka/run-cmake@master
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeAppendedArgs: '-DRELEASE_BUILD=ON -DCMAKE_BUILD_TYPE=Release -G Ninja'
        cmakeWrapperCommand: emcmake
        buildDirectory: '${{ github.workspace }}/build'
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build/bin/
