on:
  push:
    branches:
    - master
    - release/*
name: Windows build
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        vcpkg install sdl2
