on:
  push:
    branches:
    - master
    - release/*
name: Windows build
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      env:
        VCPKG_DEFAULT_TRIPLET: x64-windows
      run: |
        vcpkg install sdl2
    - name: Configure
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        mkdir build
        cd build
        cmake .. -DRELEASE_BUILD=ON -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake
    - name: Build
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cd build
        cmake --build . --config Release
    - name: Copy binaries and resources
      run: |
        mkdir bin
        xcopy /s build\bin\Release\*.* bin\
        xcopy /s tests\roms\*.* bin\roms\
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: build
        path: bin/
